-- Create services table for pages/admin/services.html
create table if not exists public.services (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  company_name text,
  authorization text,
  category text,
  verified boolean default false,
  phone text,
  contact text,
  address text,
  city text,
  state text,
  zip text,
  email text,
  notes text,
  website text,
  availability text,
  lat numeric,
  long numeric
);

-- Enable RLS
alter table public.services enable row level security;

-- Create policy to allow read/write for now
create policy "Enable all access for all users" on public.services
for all using (true) with check (true);
